### ISSUE TITLE
change of syntax for `x/y/znode` in Oceananigans v0.79 -> v0.80

### ISSUE THREAD

**Issue by navidcy** [simone-silvestri/WenoNeverworld.jl#2]
the syntax for `x/y/znode` has changed in transitioning from Oceananigans v0.79 -> v0.80

this line might is affected... 

https://github.com/simone-silvestri/WenoNeverworld.jl/blob/aeb2ff5b7a22bb308b9d6ff76ab0b0f10c97683a/src/weno_neverworld_utils.jl#L97

maybe others also?

**Comment by simone-silvestri** [comment]
right also the boundary conditions. I will fix it tomorrow

**Comment by simone-silvestri** [comment]
Fixed
